
 const NUMBER_CATEGORIES = 12; 
 const NUMBER_QUESTION = 10; 
 const PERCENT_COLOR_ANSWER = 8;
 const COUNT_ANSWER = 6;
 const NEXT_COUNT = 1; 
 const COUNT_IMAGE = 240;

 export {NUMBER_CATEGORIES, NUMBER_QUESTION, PERCENT_COLOR_ANSWER, COUNT_ANSWER, NEXT_COUNT, COUNT_IMAGE}
